/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.11.1/samples
 */
plugins{
  java
  id("org.springframework.boot") version "3.4.1"
  id("io.spring.dependency-management") version "1.1.7"
}

group = "com.wsapoa"
version = "0.0.1-SNAPSHOT"

java{
  toolchain{
    languageVersion = JavaLanguageVersion.of(21)
  }
}

configurations{
  compileOnly{
    extendsFrom(configurations.annotationProcessor.get())
  }
}

repositories{
  mavenCentral()
}


dependencies {
  implementation("org.springframework.boot:spring-boot-starter")
  implementation("org.springframework.boot:spring-boot-starter-validation")
  implementation("org.springframework.boot:spring-boot-starter-web")
  implementation("org.springframework.boot:spring-boot-starter-data-jpa")
  implementation("mysql:mysql-connector-java:8.0.33")
  testImplementation("org.springframework.boot:spring-boot-starter-test")
  compileOnly("org.projectlombok:lombok")
  annotationProcessor("org.projectlombok:lombok")
}
