spring:
  datasource:
    url: jdbc:mysql://localhost:3307/test_database?useSSL=true&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: VcgsA07P5cx5XklMUdCPfMhskGPP2B48
    driver-class-name: com.mysql.cj.jdbc.Driver