spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_database?useSSL=true&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: gPOSuBIClgViAJ6vbf2EdjsjJDPVTce8
    driver-class-name: com.mysql.cj.jdbc.Driver