spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_database?useSSL=true&allowPublicKeyRetrieval=true
    username: root
    password: o6NI1ffpiGiblc/og7ftUV0oHInLnRgS
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
